# Generated by Django 5.0.4 on 2024-04-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_city_alter_profile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles_main_photos/'),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='image',
            field=models.ImageField(upload_to='images/profiles_profile_photos/'),
        ),
    ]
