# Generated by Django 5.0.4 on 2024-04-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_main_photo_alter_profilephoto_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilephoto',
            options={'ordering': ['-id']},
        ),
    ]
