# Generated by Django 5.0.4 on 2024-04-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_profilephoto_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="life_status",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
