# Generated by Django 5.0.4 on 2024-04-19 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("days", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="days.day",
            ),
        ),
    ]
