# Generated by Django 5.0.4 on 2024-04-19 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("days", "0002_alter_task_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("failed", "провалено"), ("completed", "виконано")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to="days.day",
            ),
        ),
        migrations.AlterField(
            model_name="lifelesson",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="life_lessons",
                to="days.day",
            ),
        ),
        migrations.AlterField(
            model_name="musicalcomposition",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="musical_compositions",
                to="days.day",
            ),
        ),
        migrations.AlterField(
            model_name="relatedperson",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_people",
                to="days.day",
            ),
        ),
        migrations.AlterField(
            model_name="visitedplace",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visited_places",
                to="days.day",
            ),
        ),
    ]
