# Generated by Django 5.0.4 on 2024-04-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("days", "0003_task_status_alter_achievement_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("failed", "не виконано"), ("completed", "виконано")],
                max_length=10,
                null=True,
            ),
        ),
    ]
