# Generated by Django 5.0.4 on 2024-04-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("days", "0004_alter_task_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["execution_time"]},
        ),
        migrations.RenameField(
            model_name="day",
            old_name="access_type",
            new_name="access_mode",
        ),
    ]
