# Generated by Django 5.0.4 on 2024-04-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("days", "0005_alter_task_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="conclusion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Conclusion",
        ),
    ]
