# Generated by Django 5.0.4 on 2024-04-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("days", "0006_day_conclusion_delete_conclusion"),
    ]

    operations = [
        migrations.AddField(
            model_name="mood",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
